name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest
      - name: Run tests
        run: |
          pytest -q
  mcp-smoke:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install uvicorn fastapi requests pytest
      - name: Launch FastAPI (background)
        env:
          PORT: 8000
        run: |
          nohup python -m uvicorn main:app --host 0.0.0.0 --port $PORT > uvicorn.log 2>&1 &
          for i in $(seq 1 40); do
            sleep 1
            curl -sSf "http://127.0.0.1:${PORT}/health" && echo "API up" && break || true
          done
          curl -sSf "http://127.0.0.1:${PORT}/health"
      - name: Run MCP smoke
        env:
          MCP_BASE: http://127.0.0.1:8000
          MCP_SECRET: default-secret
        run: |
          python scripts/mcp_smoke.py

